### PR TITLE
reduce repo to KVP method only

### PR DESCRIPTION
**Pull request by mikkokotila**
This PR handles the following changes: 

- Remove all other methods except KVP (as no other method seems to work)
- Remove all files related to other methods
- Remove code referring to the other methods
- Simplify the API so that there is just a single method `get_phonetics`
- Remove everything else that is not required for the method `get_phonetics`
- Update README.md

There might be some other things as well, really the objective was to bring this package to its minimum version so we can start maintaining up to minimal standard for such a package.

### CODE REVIEW

**Comment by eroux** [comment]
Hi @mikkokotila thanks for the PR! KVP is kind of a side thing, the most interesting part is the MST schema so I won't remove it. You also added a `.DS_Store`

**Comment by mikkokotila** [comment]
The package, as it stands, has several important problems: 

- There is

**Comment by mikkokotila** [comment]
> You also added a .DS_Store

Sure, every repo must have a standard `.gitignore` which automatically prevents such a thing.

**Comment by mikkokotila** [comment]
The PR also makes it into an actual API. By that I mean there is a clear API call to make, and then no matter what the case, the API always returns something. The way it was structured failed to meet this minimum criterion of a thing being an API (and of course, everything should be an API).

**Comment by eroux** [comment]
sure! Can you open a new PR with just the API changes?

**Pull request closed without merging**
